# Generated by Django 3.1.3 on 2020-11-27 11:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('button_name', models.CharField(max_length=100)),
                ('top_bg_image', models.ImageField(upload_to='Images/')),
                ('sec1_heading', models.CharField(max_length=100)),
                ('sec1_inner1_icon', models.CharField(choices=[('laptop', 'laptop'), ('link', 'link'), ('paper-plane', 'paper-plane')], max_length=15)),
                ('sec1_inner1_title', models.CharField(max_length=100)),
                ('sec1_inner1_desc', ckeditor.fields.RichTextField()),
                ('sec1_inner2_icon', models.CharField(choices=[('laptop', 'laptop'), ('link', 'link'), ('paper-plane', 'paper-plane')], max_length=11)),
                ('sec1_inner2_title', models.CharField(max_length=100)),
                ('sec1_inner2_desc', ckeditor.fields.RichTextField()),
                ('sec1_inner3_icon', models.CharField(choices=[('laptop', 'laptop'), ('link', 'link'), ('paper-plane', 'paper-plane')], max_length=11)),
                ('sec1_inner3_title', models.CharField(max_length=100)),
                ('sec1_inner3_desc', ckeditor.fields.RichTextField()),
                ('sec2_heading', models.CharField(max_length=100)),
                ('sec2_title', models.CharField(max_length=100)),
                ('sec2_desc', ckeditor.fields.RichTextField()),
                ('sec3_heading', models.CharField(max_length=100)),
                ('sec4_num', models.IntegerField()),
                ('sec4_email', models.EmailField(max_length=254)),
                ('sec4_address', models.CharField(max_length=100)),
                ('sec4_button', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec2_inner_title', models.CharField(max_length=100)),
                ('sec2_inner_percentage', models.IntegerField()),
                ('sec3_inner_image', models.ImageField(upload_to='Images/')),
                ('sec3_inner_title', models.CharField(max_length=100)),
            ],
        ),
    ]
