# Generated by Django 3.1.3 on 2020-11-28 15:58

from django.db import migrations, models
import mysite.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=10, null=True, validators=[mysite.validators.validate_number])),
            ],
        ),
        migrations.RenameField(
            model_name='portfolio1',
            old_name='sec4_num',
            new_name='sec4_ph_num',
        ),
        migrations.AddField(
            model_name='portfolio1',
            name='animated_desc',
            field=models.CharField(default=2020, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio1',
            name='sec4_heading',
            field=models.CharField(default=2020, max_length=100),
            preserve_default=False,
        ),
    ]
