# Generated by Django 3.1.3 on 2020-11-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20201128_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio1',
            name='sec5_fb',
            field=models.CharField(default=2020, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio1',
            name='sec5_gh',
            field=models.CharField(default=2020, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio1',
            name='sec5_ig',
            field=models.CharField(default=2020, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio1',
            name='sec5_ld',
            field=models.CharField(default=2020, max_length=100),
            preserve_default=False,
        ),
    ]
