# Generated by Django 3.1.3 on 2020-11-30 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20201130_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio1',
            name='top_bg_image',
        ),
    ]
